Added validators tests.
l14D35/meta-bug pull request #26
Opened 2020-04-02 11:13 UTC by KR4K0

2020-04-02 13:46 UTC, keyjey64 commented on src/main/resources/application.properties
> +spring.profiles.active=local
...

2020-04-02 15:07 UTC, keyjey64 commented on src/main/java/com/metabug/validation/password/PasswordConstraintValidator.java
> +
?

2020-04-02 15:07 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +
redundant empty line

2020-04-02 15:07 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +    private static ConstraintValidatorContext validatorContext;
final?

2020-04-02 15:08 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +        Boolean result = emailValidator.isValid(input, validatorContext);
final

2020-04-02 15:09 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +        final EmailValidator emailValidator = new EmailValidator();
add //given above

2020-04-02 15:10 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +
//when

2020-04-02 15:21 UTC, krzjez requested changes

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +
//then

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +
redundant empty line

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +    public void shouldReturnFalseWhenEmailIsInvalid(String input) {
final String input?

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +        Boolean result = emailValidator.isValid(input, validatorContext);
final

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +
redundant empty line

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        validatorContext = mock(ConstraintValidatorContext.class);
move to BeforeAll

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aaaaaaa", validatorContext);
this should be in //when

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        doNothing().when(validatorContext).disableDefaultConstraintViolation();
I think that this should be in beforeAll

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordMatchesValidatorTest.java
> +    private UserDto user;
final?

2020-04-02 15:21 UTC, keyjey64 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +    private ConstraintValidatorContext.ConstraintViolationBuilder constraintViolationBuilder;
final?

2020-04-05 14:21 UTC, kujawad requested changes

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aa", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1AAAAAAA", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1aaaaaaa", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!!Aaaaaaa", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("11Aaaaaaa", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aaa aaaa", validatorContext);
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +    public void shouldReturnTrueWhenEmailIsValid(String input) {
`final`

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +        Boolean result = emailValidator.isValid(input, validatorContext);
You're testing `isValid` method, this should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/EmailValidatorTest.java
> +
Missing `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aaaaaaa", validatorContext);
This should be in `//when` section. You're testing `isValid` method

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aa", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1AAAAAAA", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1aaaaaaa", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!!Aaaaaaa", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("11Aaaaaaa", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordConstraintValidatorTest.java
> +        Boolean result = passwordConstraintValidator.isValid("!1Aaa aaaa", validatorContext);
Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordMatchesValidatorTest.java
> +        user.setPassword("!Password123");
These should be in `//given` section, you're preparing object to testing

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordMatchesValidatorTest.java
> +        boolean result = passwordMatchesValidator.isValid(user, validatorContext);
1. `final`
2. Should be in `//when` section

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordMatchesValidatorTest.java
> +        user.setPassword("!Password123");
Apply this in `shouldReturnFalseWhenPasswordsDontMatch` too

2020-04-05 14:21 UTC, l14D35 commented on src/test/java/com/metabug/PasswordMatchesValidatorTest.java
> +        boolean result = passwordMatchesValidator.isValid(user, validatorContext);
Apply this in `shouldReturnFalseWhenPasswordsDontMatch` too

2020-04-08 11:09 UTC, merged